[config]
# will be set to mainnet by default if omitted
#rpc = "https://fullnode.devnet.sui.io:443"

[packages]
# based on source code (syntax same as in Move.toml):
DCA = { local = "../packages/dca" }
