[package]
name = "Cetus"
version = "0.0.1"
published-at = "0xd43348b8879c1457f882b02555ba862f2bc87bcc31b16294ca14a82f608875d2" # v6

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "mainnet-v1.19.1" }
CetusClmm = { local = "../cetus_clmm" }

[addresses]
cetus = "0x996c4d9480708fb8b92aa7acf819fb0497b5ec8e65ba06601cae2fb6db3312c3"
